using BusinessLayer;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmColorMaster : DevExpress.XtraEditors.XtraForm
    {
        private ColorMaster  ColorMasterRequest;
        public FrmColorMaster()
        {
            InitializeComponent();
            ColorMasterRequest = new ColorMaster();
            ColorMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            ColorMasterRequest.Result = new ResultDetail();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtCName.Text != string.Empty)
                {
                    ColorMasterRequest.ColorName = txtCName.Text;
                    ColorMasterRequest.Update();
                }
                else 
                {
                    XtraMessageBox.Show(ColorMasterRequest.Result.Message, "please give the manditory field", MessageBoxButtons.OK, MessageBoxIcon.Information);

                }

                if (ColorMasterRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show(ColorMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }

            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btEdit_Click(object sender, EventArgs e)
        {
            try
            {
                var selectedRows = ColormasterGrid.GetSelectedRows();

                foreach (var rowHandle in selectedRows)
                {
                    ColorMasterRequest.Id = (Int32)ColormasterGrid.GetRowCellValue(rowHandle, "ID");
                    txtCName.Text = ColormasterGrid.GetRowCellValue(rowHandle, "Colournname").ToString();

                }
                btnAdd.Enabled = false;
                btEdit.Enabled = false;
                btDelete.Enabled = false;
                btUpdate.Enabled = true;
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        private void btDelete_Click(object sender, EventArgs e)
        {
            var selectedRows = ColormasterGrid.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var id = ColormasterGrid.GetRowCellValue(rowHandle, "Id");

                ColorMasterRequest.Id = (Int32)id;
            }

            ColorMasterRequest.Delete();

            if (ColorMasterRequest.Result.Status == ResultStatus.Success)
            {
                XtraMessageBox.Show(ColorMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

        }

        private void btClear_Click(object sender, EventArgs e)
        {
            txtCName.ResetText();
        }

        private void btExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}