using DataLayer;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmCustomerMaster : DevExpress.XtraEditors.XtraForm
    {
        private readonly SqlConnector _conn;
        public FrmCustomerMaster()
        {
            InitializeComponent();
            string connectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            _conn = new SqlConnector(connectionString);
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            // Calling the stored procedure for creating a new Company Profile
            SqlParameter[] parameters = new SqlParameter[]
            {
            new SqlParameter("@Code,", txtCustomerCode.Text),
            new SqlParameter("@Name", txtCustomerName.Text),
            new SqlParameter("@OffAddress", txtOffAddress.Text),
            new SqlParameter("@State", drpState.Text),
            new SqlParameter("@Pin", txtStatePin.Text),
            new SqlParameter("@Country", drpCountry.Text),
            new SqlParameter("@PhonePin", txtCode.Text),
            new SqlParameter("@OffPhone", txtPhoneNo.Text),
            new SqlParameter("@Email", txtEmailID.Text),
            new SqlParameter("@ResAddress", txtCDAddress),
            new SqlParameter("@ResState", drpState2.Text),
            new SqlParameter("@ResPin", txtPin.Text),
            new SqlParameter("@ResCountry", drpCDCountry.Text),
            new SqlParameter("@Mobile", txtMobileNo.Text),
            new SqlParameter("@TinNo", txtTINno.Text),
            new SqlParameter("@TinDate", ddTINDate.Text.ToString()),
            new SqlParameter("@CstNo", txtCSTno.Text),
            new SqlParameter("@CstDate", ddCSTDate.Text.ToString()),
            new SqlParameter("@LicenseNo", txtLicenseNo.Text),
            new SqlParameter("@Website", txtWebsite.Text),
            };

            var i = _conn.ExecuteNonQuery("PRO_UpdateCompanyProfileInfo", parameters);
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            // Clear the values in textboxes
            txtCustomerCode.ResetText();
            txtCustomerName.ResetText();
            txtOffAddress.ResetText();
            drpState.ResetText();
            txtStatePin.ResetText();
            drpCountry.ResetText();
            txtCode.ResetText();
            txtPhoneNo.ResetText();
            txtEmailID.ResetText();
            txtCDAddress.ResetText();
            drpState2.ResetText();
            txtPin.ResetText();
            drpCDCountry.ResetText();
            txtMobileNo.ResetText();
            txtTINno.ResetText();
            ddTINDate.ResetText();
            txtCSTno.ResetText();
            ddCSTDate.ResetText();
            txtLicenseNo.ResetText();
            txtWebsite.ResetText();
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            // Get the underlying GridView control from the GridControl
            var view = gridView1;

            // Get the selected rows from the GridView control
            var selectedRows = view.GetSelectedRows();

            // Loop through the selected rows in reverse order and delete them
            for (int i = selectedRows.Length - 1; i >= 0; i--)
            {
                var rowHandle = selectedRows[i];
                if (view.IsDataRow(rowHandle))
                    view.DeleteRow(rowHandle);
            }
        }
    }
}