using BusinessLayer;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmCompanyProfile : DevExpress.XtraEditors.XtraForm
    {
        private CompanyMasterInfo CompanyMasterRequest;
        public FrmCompanyProfile()
        {
            InitializeComponent();

            CompanyMasterRequest = new CompanyMasterInfo();
            CompanyMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void Newbtn_Click(object sender, EventArgs e)
        {
            FrmCompanyInfo CompanyInfo = new FrmCompanyInfo();
            //CompanyInfo.MdiParent = this;
            CompanyInfo.Show();
        }

        private void Deletebtn_Click(object sender, EventArgs e)
        {
            var selectedRows = gridView2.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                CompanyMasterRequest.Id = (Int32)gridView2.GetRowCellValue(rowHandle, "Id");
            }


            CompanyMasterRequest.Delete();
        }
    }
}