using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Configuration;
using DataLayer;

namespace BillPlex
{
    public partial class FrmClientCompanyBankInfo : DevExpress.XtraEditors.XtraForm
    {
        private readonly SqlConnector _conn;
        public FrmClientCompanyBankInfo()
        {
            InitializeComponent();
            string connectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            _conn = new SqlConnector(connectionString);
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            // Calling the stored procedure for creating a new Company Profile
            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@MainCompanyId", drpMainCompany.Text),
                new SqlParameter("@ClientCompanyId", drpClientCompany.Text),
                new SqlParameter("@BankName", drpBankName.Text),
                new SqlParameter("@BankAcNo", txtAccountNo.Text),
                new SqlParameter("@BranchCode",txtBranchCode.Text),
                new SqlParameter("@BranchName", TxtBranchName.Text),
                new SqlParameter("@IFSCode", txtIfsCode.Text),
                new SqlParameter("@Address", txtAddress.Text),
            };

            var i = _conn.ExecuteNonQuery("PRO_UpdateClientBankInfo", parameters);
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            var Id = 0;
            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@MainCompanyId", drpMainCompany.Text),
                new SqlParameter("@ClientCompanyId", drpClientCompany.Text),
                new SqlParameter("@BankName", drpBankName.Text),
                new SqlParameter("@BankAcNo", txtAccountNo.Text),
                new SqlParameter("@BranchCode",txtBranchCode.Text),
                new SqlParameter("@BranchName", TxtBranchName.Text),
                new SqlParameter("@IFSCode", txtIfsCode.Text),
                new SqlParameter("@Address", txtAddress.Text),
            };

            var i = _conn.ExecuteNonQuery("PRO_UpdateClientBankInfo", parameters);
        }
    }
}