using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmCompanyProfile : DevExpress.XtraEditors.XtraForm
    {
        private CompanyMasterInfo CompanyMasterRequest;

        private FrmCompanyInfo CompanyInfoRequest;
        private GridView gridView;

        public FrmCompanyProfile()
        {
            InitializeComponent();

            gridView = gridView1;
            //gridView.DoubleClick += Editbtn_Click;


            CompanyMasterRequest = new CompanyMasterInfo();
            CompanyMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void Newbtn_Click(object sender, EventArgs e)
        {
            FrmCompanyInfo CompanyInfo = new FrmCompanyInfo();
            //CompanyInfo.MdiParent = this;
            CompanyInfo.Show();
        }

        private void Deletebtn_Click(object sender, EventArgs e)
        {
            var selectedRows = gridView1.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                CompanyMasterRequest.Id = (Int64)gridView1.GetRowCellValue(rowHandle, "Id");
                
                //CompanyMasterRequest.Id = (Int32)gridView2.GetRowCellValue(rowHandle, "Id");
            }
            CompanyMasterRequest.Delete();

            if (CompanyMasterRequest.Result.Status == ResultStatus.Success)
            {
                XtraMessageBox.Show(CompanyMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void Editbtn_Click(object sender, EventArgs e)
        {
            var selectedRow = gridView1.GetSelectedRows();

            CompanyInfoRequest = new FrmCompanyInfo();

            CompanyInfoRequest.BindData(gridView1);

            //CompanyInfo.MdiParent = this;
            CompanyInfoRequest.Show();
        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {
            //gridView1.Columns.Clear(); // Clear existing columns (optional)
            //gridView1.Columns.AddVisible("Name", "Name");
            //gridView1.Columns.AddVisible("Age", "Age");
        }
    }
}