using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmDirectJobReceivedWithoutGivingProfile : DevExpress.XtraEditors.XtraForm
    {
        private DirectJobReceivedWithoutGiving DirectJobReceivedWithoutGivingRequest;
        private FrmDirectJobReceivedWithoutGivingInfo DirectJobReceivedWithoutGivingInfoRequest;
        private GridView gridView;
        public FrmDirectJobReceivedWithoutGivingProfile()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        public void ReloadSqlDataSource()
        {
            sqlDataSource1.FillAsync();
            gridView1.RefreshData();
        }
        private void Newbtn_Click(object sender, EventArgs e)
        {
            FrmDirectJobReceivedWithoutGivingInfo CP = new FrmDirectJobReceivedWithoutGivingInfo();
            CP.MdiParent = this.MdiParent;
            CP.Show();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            var selectedRow = gridView1.GetSelectedRows();

            DirectJobReceivedWithoutGivingInfoRequest = new FrmDirectJobReceivedWithoutGivingInfo();

            DirectJobReceivedWithoutGivingInfoRequest.BindData(gridView1);
            DirectJobReceivedWithoutGivingInfoRequest.MdiParent = this.MdiParent;
            DirectJobReceivedWithoutGivingInfoRequest.Show();
        }
    }
}