using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmJobReallocation : DevExpress.XtraEditors.XtraForm
    {
        private JobGivingWithoutDc JobGivingWithoutDcRequest;
        public FrmJobReallocation()
        {
            InitializeComponent();

            JobGivingWithoutDcRequest = new JobGivingWithoutDc();

            JobGivingWithoutDcRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;

            Dictionary<string, bool> dropDownList = new Dictionary<string, bool>
            {
                    { "EmployeePersonalRequired", true },
                    { "OrderMasterRequired", true }
            };

            var dropdwonList = JobGivingWithoutDcRequest.GetDropdownCollections(dropDownList);

            foreach (DictionaryEntry item in dropdwonList)
            {
                if (item.Key == "EmployeePersonalRequired")
                {
                    JobGivingWithoutDcRequest.EmployeePersonalList = (List<DropDownItemInfo>)item.Value;
                }
                if (item.Key == "OrderMasterRequired")
                {
                    JobGivingWithoutDcRequest.OrderMasterList = (List<DropDownItemInfo>)item.Value;
                }
            }
            if (JobGivingWithoutDcRequest.EmployeePersonalList != null)
            {
                if (JobGivingWithoutDcRequest.EmployeePersonalList.Count() > 0)
                {
                    foreach (DropDownItemInfo item in JobGivingWithoutDcRequest.EmployeePersonalList)
                    {
                        drpEmpCode.Properties.Items.Add(new ImageComboBoxItem(item.Code));
                    }
                }
            }
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                var selectedRows = gridView1.GetSelectedRows();

                foreach (var rowHandle in selectedRows)
                {
                    JobGivingWithoutDcRequest.Id = (Int64)gridView1.GetRowCellValue(rowHandle, "Id");
                    txtEmpCode.Text = gridView1.GetRowCellValue(rowHandle, "EmployeeCode").ToString();
                    txtEmpName.Text = (string)gridView1.GetRowCellValue(rowHandle, "EmployeeName");
                    txtCustName.Text = (string)gridView1.GetRowCellValue(rowHandle, "CustomerName");
                    txtRawMaterial.Text = (string)gridView1.GetRowCellValue(rowHandle, "RawMaterial");
                    txtRawType.Text = (string)gridView1.GetRowCellValue(rowHandle, "Type");
                    txtProductCode.Text = (string)gridView1.GetRowCellValue(rowHandle, "ModelCode");
                    txtProModel.Text = (string)gridView1.GetRowCellValue(rowHandle, "ModelName");
                    txtQuanity.Text = (string)gridView1.GetRowCellValue(rowHandle, "QuantityPiece");
                    txtQuantity.Text = (string)gridView1.GetRowCellValue(rowHandle, "QuantityPiece");
                    txtProSize.Text = (string)gridView1.GetRowCellValue(rowHandle, "ProductSize");
                    txtProColor.Text = (string)gridView1.GetRowCellValue(rowHandle, "Color");
                    //txtWeight.Text = (string)gridView1.GetRowCellValue(rowHandle, "WeightKg");
                    lblWeight.Text = (string)gridView1.GetRowCellValue(rowHandle, "WeightKg");
                    //txtReceivedQty.Text = (string)gridView1.GetRowCellValue(rowHandle, "Id");
                    //txtPendingQty.Text = (string)gridView1.GetRowCellValue(rowHandle, "Id");
                    //txtOrder.Text = gridView1.GetRowCellValue(rowHandle, "OrderNo").ToString();
                    JobGivingWithoutDcRequest.OrderNo = (Int32)gridView1.GetRowCellValue(rowHandle, "OrderNo");
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void drpEmpCode_SelectedIndexChanged(object sender, EventArgs e)
        {
            string selectedItem = (string)drpEmpCode.SelectedItem;
            if (selectedItem != null)
            {
                txtComName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.proModel ?? "";
                txtClientCompany.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.productId ?? "";
                txtSubClient.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.SubCom ?? "";
                txtJEmpName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.Name ?? "";
                txtDirector.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.AuthorName ?? "";
                txtClientName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.RawMaterial ?? "";
                txtSubContractor.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.SubComName ?? "";
                //txtOrder.Text = JobGivingWithoutDcRequest.OrderMasterList.FirstOrDefault(item => item.Code == selectedItem.ToString())?.Code ?? "";
            }
        }

        private void btnTransfer_Click(object sender, EventArgs e)
        {
            try
            {
                string selectedItem = (string)drpEmpCode.SelectedItem;

                if (selectedItem != null)
                {
                    JobGivingWithoutDcRequest.EmployeeCode = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.Id ?? -1;
                }
                JobGivingWithoutDcRequest.CompanyName = txtComName.Text;
                JobGivingWithoutDcRequest.ClientCompany = txtClientCompany.Text;
                JobGivingWithoutDcRequest.SubClientCompany = txtSubClient.Text;
                JobGivingWithoutDcRequest.EmployeeName = txtJEmpName.Text;
                JobGivingWithoutDcRequest.Director = txtDirector.Text;
                JobGivingWithoutDcRequest.ClientName = txtClientName.Text;
                JobGivingWithoutDcRequest.subContractor = txtSubContractor.Text;
                JobGivingWithoutDcRequest.QuantityPiece = txtQuantity.Text;
                JobGivingWithoutDcRequest.WeightKg = txtWeight.Text;
                JobGivingWithoutDcRequest.Excess = txtExcess.Text;
                JobGivingWithoutDcRequest.Shortage = txtShortage.Text;
                //JobGivingWithoutDcRequest.OrderNo = Text;
                JobGivingWithoutDcRequest.Update();

                if (JobGivingWithoutDcRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show("", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.Close();
                }
                else
                {
                    XtraMessageBox.Show(JobGivingWithoutDcRequest.Result.Message, "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void txtWeight_EditValueChanged(object sender, EventArgs e)
        {
            var count = 0;
            if (txtWeight.Text != "" && lblWeight.Text != "")
            {
                var a = Convert.ToInt32(txtWeight.Text);
                var b = Convert.ToInt32(lblWeight.Text);
                count = (a - b)
                    ;
                txtShortage.Text = count.ToString();
            }
        }

        private void btnClear_Click_1(object sender, EventArgs e)
        {
            drpEmpCode.ResetText();
            txtEmployeeCode.ResetText();
            txtJEmpName.ResetText();
            txtExcess.ResetText();
            txtPendingQty.ResetText();
            txtProColor.ResetText();
            txtQuantity.ResetText();
            txtEmpCode.ResetText();
            txtEmpName.ResetText();
            txtCustName.ResetText();
            txtRawMaterial.ResetText();
            txtRawType.ResetText();
            txtProductCode.ResetText();
            txtProModel.ResetText();
            txtQuanity.ResetText();
            txtQuantity.ResetText();
            txtProSize.ResetText();
            txtProColor.ResetText();
            txtWeight.ResetText();
            lblWeight.ResetText();
            txtReceivedQty.ResetText();
            txtPendingQty.ResetText();
        }
    }
}