using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmJobReceivedInfo : DevExpress.XtraEditors.XtraForm
    {
        private JobReceived JobReceivedRequest;
       
        public FrmJobReceivedInfo()
        {
            InitializeComponent();
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string EmployeeCode = (string)txtEmpCode.Text;
                //JobReceivedRequest.EmployeeCode = txtEmpCode.Text;
                if (JobReceivedRequest != null)
                {
                    JobReceivedRequest.EmployeeName = txtEmpName.Text;
                }
                
                JobReceivedRequest.CustomerName = txtCName.Text;
                JobReceivedRequest.RawMaterialName = txtRawMaterial.Text;
                JobReceivedRequest.Quantity = txtQuantity.Text;
                JobReceivedRequest.Wages = txtWages.Text;
                JobReceivedRequest.PendingQty = txtPQty.Text;
                JobReceivedRequest.ModelName = txtMName.Text;
                JobReceivedRequest.Type = txtType.Text;
                JobReceivedRequest.Weight = txtWeight.Text;
                JobReceivedRequest.CurrentWt = txtCrntWt.Text;
                JobReceivedRequest.RcvdQty = txtRcvdQty.Text;
                JobReceivedRequest.ReceivingDate = ddReceDate.Text;
                JobReceivedRequest.ProductModel = txtPModel.Text;
                JobReceivedRequest.ProductCode = txtPCode.Text;
                JobReceivedRequest.ProductSize = txtPSize.Text;
                JobReceivedRequest.ProductColor = txtColor.Text;
                JobReceivedRequest.IncentiveApplicable = drpIncentiveApp.Text;
                JobReceivedRequest.BeforeDays = txtBeforeDys.Text;
                JobReceivedRequest.AfterDays = txtAfterdys.Text;
                JobReceivedRequest.BalanceWeight = txtBalanceWeight.Text;
                JobReceivedRequest.Conveyance = txtConveyance.Text;
                JobReceivedRequest.Deduction = txtDeduction.Text;
                JobReceivedRequest.Incentive = txtIncentive.Text;
                JobReceivedRequest.Total = txtTotal.Text;
                JobReceivedRequest.NetAmt = txtNetAmt.Text;
                JobReceivedRequest.Update();

                if (JobReceivedRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show(JobReceivedRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    this.Close();

                    FrmSubClientCompanyProfile form = Application.OpenForms.OfType<FrmSubClientCompanyProfile>().FirstOrDefault();

                    Form myForm = Application.OpenForms["FrmJobReceivedRequestProfile"];
                    if (myForm != null)
                    {
                        form.ReloadSqlDataSource();
                    }
                }
                else
                {
                    XtraMessageBox.Show(JobReceivedRequest.Result.Message, "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);

                }
            }
            catch (Exception ex)
            {
                // Display a warning alert
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);

            }
        }
         public void BindData(dynamic selectedCompanyList)
         {
             var selectedRows = selectedCompanyList.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {

                txtEmpName.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComFactoryNo");
                txtCName.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComCstNo");
                txtRawMaterial.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComSslNo");
                txtQuantity.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComTinNo");
                txtWages.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComLicenseno");
                txtPQty.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComPanNo");
                txtMName.Text = selectedCompanyList.GetRowCellValue(rowHandle, "ComTanNo");
                txtType.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorName");
                txtWeight.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtCrntWt.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtRcvdQty.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                ddReceDate.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtPModel.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtPCode.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtPSize.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtColor.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                drpIncentiveApp.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtBeforeDys.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtAfterdys.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtBalanceWeight.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtConveyance.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtDeduction.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtIncentive.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtTotal.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");
                txtNetAmt.Text = selectedCompanyList.GetRowCellValue(rowHandle, "AuthorFathername");

                btnAdd.Enabled = false;
                btnNew.Enabled = false;
                btnUpdate.Enabled = true;
                btnEdit.Enabled = true;

            }


        }

    }
}
