using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmJobReallocation : DevExpress.XtraEditors.XtraForm
    {
        private JobGivingWithoutDc JobGivingWithoutDcRequest;
        public FrmJobReallocation()
        {
            InitializeComponent();

            JobGivingWithoutDcRequest = new JobGivingWithoutDc();

            JobGivingWithoutDcRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;

            Dictionary<string, bool> dropDownList = new Dictionary<string, bool>
            {
                    { "EmployeePersonalRequired", true },
                    { "OrderMasterRequired", true }
            };

            var dropdwonList = JobGivingWithoutDcRequest.GetDropdownCollections(dropDownList);

            foreach (DictionaryEntry item in dropdwonList)
            {
                if (item.Key == "EmployeePersonalRequired")
                {
                    JobGivingWithoutDcRequest.EmployeePersonalList = (List<DropDownItemInfo>)item.Value;
                }
                if (item.Key == "OrderMasterRequired")
                {
                    JobGivingWithoutDcRequest.OrderMasterList = (List<DropDownItemInfo>)item.Value;
                }
            }
            if (JobGivingWithoutDcRequest.EmployeePersonalList != null)
            {
                if (JobGivingWithoutDcRequest.EmployeePersonalList.Count() > 0)
                {
                    foreach (DropDownItemInfo item in JobGivingWithoutDcRequest.EmployeePersonalList)
                    {
                        drpEmpCode.Properties.Items.Add(new ImageComboBoxItem(item.Code));
                    }
                }
            }
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                var selectedRows = gridView1.GetSelectedRows();

                foreach (var rowHandle in selectedRows)
                {
                    JobGivingWithoutDcRequest.Id = (Int64)gridView1.GetRowCellValue(rowHandle, "Id");
                    txtEmpCode.Text = gridView1.GetRowCellValue(rowHandle, "EmployeeCode").ToString();
                    txtEmpName.Text = (string)gridView1.GetRowCellValue(rowHandle, "EmployeeName");
                    txtCustName.Text = (string)gridView1.GetRowCellValue(rowHandle, "CustomerName");
                    txtRawMaterial.Text = (string)gridView1.GetRowCellValue(rowHandle, "RawMaterial");
                    txtRawType.Text = (string)gridView1.GetRowCellValue(rowHandle, "Type");
                    txtProductCode.Text = (string)gridView1.GetRowCellValue(rowHandle, "ModelCode");
                    txtProModel.Text = (string)gridView1.GetRowCellValue(rowHandle, "ModelName");
                    txtQuanity.Text = (string)gridView1.GetRowCellValue(rowHandle, "TotalQty");
                    txtQuantity.Text = (string)gridView1.GetRowCellValue(rowHandle, "QuantityPiece");
                    txtProSize.Text = (string)gridView1.GetRowCellValue(rowHandle, "ProductSize");
                    txtProColor.Text = (string)gridView1.GetRowCellValue(rowHandle, "Color");
                    //txtWeight.Text = (string)gridView1.GetRowCellValue(rowHandle, "WeightKg");
                    lblWeight.Text = (string)gridView1.GetRowCellValue(rowHandle, "WeightKg");
                    txtReceivedQty.Text = (string)gridView1.GetRowCellValue(rowHandle, "received");
                    JobGivingWithoutDcRequest.OrderNo = (string)gridView1.GetRowCellValue(rowHandle, "OrderNo");
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void drpEmpCode_SelectedIndexChanged(object sender, EventArgs e)
        {
            string selectedItem = (string)drpEmpCode.SelectedItem;
            if (selectedItem != null)
            {
                txtComName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.proModel ?? "";
                txtClientCompany.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.productId ?? "";
                txtSubClient.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.SubCom ?? "";
                txtJEmpName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.Name ?? "";
                txtDirector.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.AuthorName ?? "";
                txtClientName.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.RawMaterial ?? "";
                txtSubContractor.Text = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.SubComName ?? "";
            }
        }

        private void btnTransfer_Click(object sender, EventArgs e)
        {
            try
            {
                string selectedItem = (string)drpEmpCode.SelectedItem;

                if (selectedItem != null)
                {
                    JobGivingWithoutDcRequest.EmployeeCode = JobGivingWithoutDcRequest.EmployeePersonalList.FirstOrDefault(item => item.Name == selectedItem.ToString())?.Id ?? -1;
                }
                JobGivingWithoutDcRequest.CompanyName = txtComName.Text;
                JobGivingWithoutDcRequest.ClientCompany = txtClientCompany.Text;
                JobGivingWithoutDcRequest.SubClientCompany = txtSubClient.Text;
                JobGivingWithoutDcRequest.EmployeeName = txtJEmpName.Text;
                JobGivingWithoutDcRequest.Director = txtDirector.Text;
                JobGivingWithoutDcRequest.ClientName = txtClientName.Text;
                JobGivingWithoutDcRequest.subContractor = txtSubContractor.Text;
                JobGivingWithoutDcRequest.QuantityPiece = txtQuantity.Text;
                JobGivingWithoutDcRequest.WeightKg = txtWeight.Text;
                JobGivingWithoutDcRequest.Excess = txtExcess.Text;
                JobGivingWithoutDcRequest.Shortage = txtShortage.Text;
                JobGivingWithoutDcRequest.Update();

                if (JobGivingWithoutDcRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show("Giving is Transfer to the another Employee", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.Close();
                }
                else
                {
                    XtraMessageBox.Show(JobGivingWithoutDcRequest.Result.Message, "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void txtWeight_EditValueChanged(object sender, EventArgs e)
        {
            int txtWeightValue;
            int lblWeightValue;

            if (int.TryParse(txtWeight.Text, out txtWeightValue) && int.TryParse(lblWeight.Text, out lblWeightValue))
            {
                int countDifferent = txtWeightValue - lblWeightValue;
                if (countDifferent >= 0)
                {
                    txtExcess.Text = countDifferent.ToString();
                    txtShortage.Text = string.Empty;
                }
                else
                {
                    txtExcess.Text = string.Empty;
                    txtShortage.Text = (countDifferent).ToString();
                }
            }
        }

        private void btnClear_Click_1(object sender, EventArgs e)
        {
            drpEmpCode.ResetText();
            txtEmployeeCode.ResetText();
            txtJEmpName.ResetText();
            txtExcess.ResetText();
            txtPendingQty.ResetText();
            txtProColor.ResetText();
            txtQuantity.ResetText();
            txtEmpCode.ResetText();
            txtEmpName.ResetText();
            txtCustName.ResetText();
            txtRawMaterial.ResetText();
            txtRawType.ResetText();
            txtProductCode.ResetText();
            txtProModel.ResetText();
            txtQuanity.ResetText();
            txtQuantity.ResetText();
            txtProSize.ResetText();
            txtProColor.ResetText();
            txtWeight.ResetText();
            lblWeight.ResetText();
            txtReceivedQty.ResetText();
            txtPendingQty.ResetText();
            txtShortage.ResetText();
        }

        private void btnJobCancel_Click(object sender, EventArgs e)
        {
            if (JobGivingWithoutDcRequest.Id != 0)
            {
                JobGivingWithoutDcRequest.Delete();

                if (JobGivingWithoutDcRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show("Job is cannceled", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    sqlDataSource1.FillAsync();
                    gridView1.RefreshData();
                }
                else
                {
                    XtraMessageBox.Show(JobGivingWithoutDcRequest.Result.Message, "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
        }

        private void txtReceivedQty_EditValueChanged(object sender, EventArgs e)
        {
            int txtWeightValue;
            int lblWeightValue;

            if (int.TryParse(txtQuanity.Text, out txtWeightValue) && int.TryParse(txtReceivedQty.Text, out lblWeightValue))
            {
                int countDifferent = txtWeightValue - lblWeightValue;
                txtPendingQty.Text = countDifferent.ToString();
                txtQuantity.Text = countDifferent.ToString();
            }
        }

        private void txtQuantity_EditValueChanged(object sender, EventArgs e)
        {
            var selectedItem = txtQuantity.Text;
            if (selectedItem != null && selectedItem != "")
            {
                var enteredQty = Convert.ToInt32(txtQuantity.Text);
                var totalWt = JobGivingWithoutDcRequest.OrderMasterList.FirstOrDefault(item => item.RawName == txtRawMaterial.Text && item.RawType == txtRawType.Text && item.color == txtProColor.Text && item.SubComName == txtProSize.Text)?.TotalWt;
                var total = enteredQty * totalWt;
                lblWeight.Text = total.ToString();
            }
        }

        private void txtEmployeeCode_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}