using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmOrderMaster : DevExpress.XtraEditors.XtraForm
    {
        private OrderMasterInfo OrderMasterRequest;

        private FrmOrderMasterInfo OrderMasterInfoRequest;
        private GridView gridView;
        public FrmOrderMaster()
        {
            InitializeComponent();
            OrderMasterRequest = new OrderMasterInfo();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            var selectedRows = gridView1.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var Id = gridView1.GetRowCellValue(rowHandle, "Id");

                OrderMasterRequest.Id = (int)Id;
            }

            OrderMasterRequest.Delete();
        }

        private void btnNew_Click(object sender, EventArgs e)
        {
            FrmOrderMasterInfo cp = new FrmOrderMasterInfo();
            cp.ShowDialog();

        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            var selectedRow = gridView1.GetSelectedRows();

            OrderMasterInfoRequest = new FrmOrderMasterInfo();

            OrderMasterInfoRequest.BindData(gridView1);

            //CompanyInfo.MdiParent = this;
            OrderMasterInfoRequest.Show();
        }
    }
}