using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BillPlex
{
    public partial class FrmOrderMaster : DevExpress.XtraEditors.XtraForm
    {
        private OrderMasterInfo OrderMasterRequest;

        private FrmOrderMasterInfo OrderMasterInfoRequest;
        private GridView gridView;
        public FrmOrderMaster()
        {
            InitializeComponent();
            OrderMasterRequest = new OrderMasterInfo();
            OrderMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        public void ReloadSqlDataSource()
        {
            sqlDataSource1.FillAsync();
            gridView1.RefreshData();

        }
        private void btnDelete_Click(object sender, EventArgs e)
        {
            var selectedRows = gridView1.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var Id = gridView1.GetRowCellValue(rowHandle, "Id");

                OrderMasterRequest.Id = (int)Id;
            }

            OrderMasterRequest.Delete();
            ReloadSqlDataSource();
        }

        private void btnNew_Click(object sender, EventArgs e)
        {
            bool IsOpen = false;

            Form myForm = Application.OpenForms["FrmOrderMasterInfo"];
            if (myForm != null)
            {
                myForm.Close();
                myForm = new FrmOrderMasterInfo();
                myForm.MdiParent = this.MdiParent;
                myForm.Show();
                IsOpen = true;
            }

            if (IsOpen == false)
            {
                FrmOrderMasterInfo CompanyInfo = new FrmOrderMasterInfo();
                CompanyInfo.MdiParent = this.MdiParent;
                CompanyInfo.Show();
            }

            //FrmOrderMasterInfo om = new FrmOrderMasterInfo();
            //om.MdiParent = this.MdiParent;
            //om.Show();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            var selectedRow = gridView1.GetSelectedRows();

            FrmOrderMasterInfo OrderMasterInfo = new FrmOrderMasterInfo();

            OrderMasterInfo.MdiParent = this.MdiParent;
            OrderMasterInfo.BindData(gridView1);
            OrderMasterInfo.Show();
            ReloadSqlDataSource();
        }

        private void FrmOrderMaster_Load(object sender, EventArgs e)
        {
            int centerX = (this.Width - panelControl3.Width) / 2;
            int centerY = (this.Height - panelControl3.Height) / 2;

            // Set the controls' positions to the calculated center position
            panelControl3.Location = new Point(centerX, centerY);
        }
    }
}