using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Configuration;
using BusinessLayer;

namespace BillPlex
{
    public partial class FrmProductMaster : DevExpress.XtraEditors.XtraForm
    {
        private ProductMaster productMasterRequest;
        public FrmProductMaster()
        {
            InitializeComponent();
            productMasterRequest = new ProductMaster();
            productMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            productMasterRequest.Result = new ResultDetail();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        public void ReloadSqlDataSource()
        {
            sqlDataSource1.FillAsync();
            grd_productmaster.RefreshData();

        }
        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtPName.Text != string.Empty)
                {
                    productMasterRequest.ProductName = txtPName.Text;
                    productMasterRequest.Update();
                }
                else 
                {
                    XtraMessageBox.Show(productMasterRequest.Result.Message, "please give the manditory field", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }

                if (productMasterRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show(productMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    ReloadSqlDataSource();
                }
            }

            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btEdit_Click(object sender, EventArgs e)
        {
            try
            {
                var selectedRows = grd_productmaster.GetSelectedRows();

                foreach (var rowHandle in selectedRows)
                {
                    productMasterRequest.Id = (Int32)grd_productmaster.GetRowCellValue(rowHandle, "Id");
                    txtPName.Text = grd_productmaster.GetRowCellValue(rowHandle, "Productmodel").ToString();
                }
                btnAdd.Enabled = true;
                btEdit.Enabled = false;
                btDelete.Enabled = true;
                btUpdate.Enabled = true;

            }
            catch (Exception ex)
            {

            }
        }

        private void btDelete_Click(object sender, EventArgs e)
        {
            var selectedRows = grd_productmaster.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var id = grd_productmaster.GetRowCellValue(rowHandle, "Id");

                productMasterRequest.Id = (Int32)id;
            }

            productMasterRequest.Delete();

            if (productMasterRequest.Result.Status == ResultStatus.Success)
            {
                XtraMessageBox.Show(productMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                ReloadSqlDataSource();
            }
        }

        private void btClear_Click(object sender, EventArgs e)
        {
            txtPName.ResetText();
        }

        private void btExit_Click(object sender, EventArgs e)
        {
            //productMasterRequest.CloseConnection();
            this.Close();

        }

        private void txtSearch_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}