using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Configuration;
using BusinessLayer;

namespace BillPlex
{
    public partial class FrmSizeMaster : DevExpress.XtraEditors.XtraForm
    {
        private SizeMaster sizeMasterRequest;
        public FrmSizeMaster()
        {
            InitializeComponent();
            sizeMasterRequest = new SizeMaster();
            sizeMasterRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;
            //sizeMasterRequest.Result = new ResultDetail();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
             sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtSName.Text != string.Empty)
                {
                    sizeMasterRequest.SizeName = txtSName.Text;
                    sizeMasterRequest.Update();

                }
                else 
                {
                    XtraMessageBox.Show(sizeMasterRequest.Result.Message, "please give the manditory field", MessageBoxButtons.OK, MessageBoxIcon.Information);

                }

                if (sizeMasterRequest.Result.Status == ResultStatus.Success)
                {
                    XtraMessageBox.Show(sizeMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }

            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btClear_Click(object sender, EventArgs e)
        {
            txtSName.ResetText();
        }

        private void btDelete_Click(object sender, EventArgs e)
        {
            var selectedRows = SizeMasterGrid.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var id = SizeMasterGrid.GetRowCellValue(rowHandle, "Id");

                sizeMasterRequest.Id = (Int32)id;
            }

            sizeMasterRequest.Delete();

            if (sizeMasterRequest.Result.Status == ResultStatus.Success)
            {
                XtraMessageBox.Show(sizeMasterRequest.Result.Message, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void btEdit_Click(object sender, EventArgs e)
        {
            try
            {
                var selectedRows = SizeMasterGrid.GetSelectedRows();

                foreach (var rowHandle in selectedRows)
                {
                    sizeMasterRequest.Id = (Int32)SizeMasterGrid.GetRowCellValue(rowHandle, "Id");
                    txtSName.Text = SizeMasterGrid.GetRowCellValue(rowHandle, "SizeName").ToString();
                    
                }
                btnAdd.Enabled = false;
                btEdit.Enabled = false;
                btDelete.Enabled = false;
                btUpdate.Enabled = true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private void btExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}