using BusinessLayer;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace BillPlex
{
    public partial class FrmSubClientCompanyProfile : DevExpress.XtraEditors.XtraForm
    {
        private SubClientCompanyInfo SubClientRequest;

        private FrmSubClientCompanyInfo SubCompanyInfoRequest;
        private GridView gridView;
        public FrmSubClientCompanyProfile()
        {
            InitializeComponent();

            gridView = SubClientGrid;
            SubClientRequest = new SubClientCompanyInfo();

            SubClientRequest.ConnectionString = ConfigurationManager.ConnectionStrings["BillPlex"].ConnectionString;

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            //sqlDataSource1.FillAsync();
        }

        private void Newbtn_Click(object sender, EventArgs e)
        {
            FrmSubClientCompanyInfo CP = new FrmSubClientCompanyInfo();
            CP.ShowDialog();
        }

        private void Deletebtn_Click(object sender, EventArgs e)
        {
            var selectedRows = SubClientGrid.GetSelectedRows();

            foreach (var rowHandle in selectedRows)
            {
                var Id = SubClientGrid.GetRowCellValue(rowHandle, "Id");
                SubClientRequest.Id = (int)Id;

            }

           // SubClientRequest.Id = Id;
            SubClientRequest.Delete();
        }

        private void btn_EditClick(object sender, EventArgs e)
        {
            var selectedRow = SubClientGrid.GetSelectedRows();

            SubCompanyInfoRequest = new FrmSubClientCompanyInfo();

            SubCompanyInfoRequest.BindData(SubClientGrid);

            //CompanyInfo.MdiParent = this;
            SubCompanyInfoRequest.Show();
        }

        //private void Clearbtn_Click(object sender, EventArgs e)
        //{

        //}

        //private void Exitbtn_Click(object sender, EventArgs e)
        //{

        //}
    }
}